name: 
  Scrape PR Info
description: >
  Scrapes the PR and compiles a list of keywords
  that are associated with the PR
inputs:
  URL: 
    description: "URL of the pull request"
    required: true
    type: string
outputs:
  keywords:
    description: >
      The list of keywords hinting at what reviews 
      should be run for the given pull request
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bs4
      - run: keywords=$(python ./.github/scripts/scrape_pr.py)
      - run: echo "::set-output name=keywords::$keywords"
      