name: Review PR for commonly encountered issues
on:
  pull_request:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  initiate-automatic-pr-process:
    name: Start automated review process
    runs-on: ubuntu-latest
    env:
      owner: ${{ github.event.repository.owner.login }}
      repo: ${{ github.event.repository.name }}
      pr: ${{ github.event.pull_request.number }}
      prPayload: ${{ toJSON(github.event.pull_request)}}
    steps:
      - id: collect-pr-info
        name: Get linked issues and labels for related to the PR
        # TODO: Implement an action to collect PR info
        #       Scrape PR for linked issues and get labels
        #       both from issues and from the PR itself. 
        run: | 
          echo "I'm not implemented yet"
        # uses: actions/hatchways/collect-pr-info@v1
        # with:
        #   owner: ${{ env.owner }}
        #   repo: ${{ env.repo }}
        #   pull_request: ${{ env.pr }}
      - id: temporary-get-labels
        name: >
          Set an env variable that contains the labels
          of the PR as a temporary step
        # NOTE: Until we have a robust way to collect PR info
        #        let's use just the labels for tests.
        run: >
          echo "labels=$(echo $prPayload | jq [.labels[].name])"
          >> $GITHUB_ENV
      - id: init-review
        name: Initialize the review (Review state will be 'pending')
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          accept: application/vnd.github.v3+json
          owner: ${{ env.owner.login }}
          repo: ${{ env.repo }}
          pull_number: ${{ env.pr }}            
          GITHUB_TOKEN: ${{ github.token }}
      - id: start-automated-reviews
        name: Start the automated review process
        # TODO: Implement an action that calls appropriate workflows
        #       based on collected PR information
        run: |
          echo "I'm not implemented yet!"
        # uses: actions/hatchways/start-review@v1
        # with:
        #   issue: ${{ env.issue }}
        #   labels: ${{ env.labels }}
        #   owner: ${{ env.owner }}
        #   repo: ${{ env.repo }}
        #   pull_request:  ${{ env.pr }}

