name: Test a job here so we don't have to create PRs
on: [push]
permissions:
  pull-requests: read
jobs:
  collect-pr-info:
    name: "Get linked issues for PR and labels"
    runs-on: ubuntu-latest
    env:
      ORG: hatchways
      REPO: team-reindeer
      NUM: 64
      SCRIPT_PATH: .github/scripts/scrape_pr.py
    steps:
      - id: checkout-scraper-script
        name: Checkout the PR scraper script
        uses: actions/checkout@v2
      - id: scrape-pr
        name: Scrape PR using python
        run: |
          python3 $SCRIPT_PATH -o $ORG -r $REPO -n $NUM