name: Leave automated reviews
on:
  pull_request:
    types: [opened]
jobs:
  leave-review:
    runs-on: ubuntu-latest
    steps:
      - name: print-pr-review-api-url
        env: 
          PR_API_URL: ${{ github.event.pull_request.pull_request.self }}
        run: echo "$PR_API_URL/reviews"

         

